# Generated by Django 3.1.3 on 2020-11-21 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedTime', models.DateTimeField()),
                ('feedType', models.CharField(max_length=50)),
                ('feedAmt', models.FloatField()),
                ('feedLoc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('flockSize', models.IntegerField()),
            ],
        ),
    ]
